modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "stack_config"
version = "${version}"
displayName = "Stack Config"
authors = "linkedto"
description = '''
Configure per-item max stack sizes via a config file.
'''

[[dependencies.stack_config]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stack_config]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2, 1.20)"
ordering = "NONE"
side = "BOTH"
