org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/opt/homebrew/opt/openjdk@25
org.gradle.parallel=true
mod_version=1.0-SNAPSHOT
maven_group=net.linkedto
archives_name=stackable
enabled_platforms=fabric
minecraft_version=26.2
fabric_loader_version=0.19.3
architectury_api_version=21.0.2
fabric_api_version=0.154.1+26.2
